# fly.toml app configuration file generated for my-work-journal-mcd on 2023-12-24T16:32:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-work-journal-mcd"
primary_region = "arn"

[build]

[[mounts]]
source = "data"
destination = "/data"
auto_extend_size_threshold = 0
initial_size = 1
volume_size = 1

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 2048
